[project]
name = "get-started"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "google-genai>=1.23.0",
    "mcp>=1.10.1",
    "pydantic>=2.11.7",
    "python-dotenv>=1.1.1",
]
